resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
    - msbuild
    - visualstudio

trigger: 
  branches:
    include: 
    - master
    
pr:
  branches:
    include: 
    - master

stages:
  - stage: Build
    jobs:
      - job:
        displayName: "Build and test application and templates"
        steps:
        - template: /AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
          parameters:
            ArmTemplateRoot: "$(System.DefaultWorkingDirectory)/Resources/ArmTemplates"
            SolutionBaseName: 'DFC.Api.Visits'

        - template: /AzureDevOpsTemplates/Build/StepTemplates/dfc-dotnetcore-build-sonar.yml@dfc-devops
          parameters:
            SolutionBaseName: 'DFC.Api.Visits'
            BuildPlatform: 'any cpu'
            BuildConfiguration: 'release'
            PublishWebApp: true
            TestSuffix: 'Tests'
            DotNetCoreVersion: '3.1.100'