variables:
  ArmTemplateRoot: "$(System.DefaultWorkingDirectory)/Resources/ArmTemplates"
  SolutionBaseName: 'DFC.App.Pages'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
    - msbuild
    - visualstudio

trigger: 
  branches:
    include: 
    - dev

pr:
  branches:
    include: 
    - dev

stages:
- stage: Build
  jobs:
  - job:
    displayName: Build and test application & templates"
    steps:
    - template: /AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '${{ variables.ArmTemplateRoot }}'
        SolutionBaseName: '${{ variables.SolutionBaseName }}'

    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: 'DFC.Api.Visits'
        BuildPlatform: 'any cpu'
        BuildConfiguration: 'release'
        DotNetCoreVersion: '3.1.100'
        PublishWebApp: true
        TestSuffix: UnitTests

    - task: PublishPipelineArtifact@1
      displayName: Publish OpenAPI docs to Pipeline Artifact
      inputs:
        targetPath: "$(System.DefaultWorkingDirectory)/DFC.Api.Visits/OpenAPIDocs"
        artifactName: ${{ variables.SolutionBaseName }}.Resources.OpenAPIDocs

    - task: PublishPipelineArtifact@1
      displayName: Publish API import script to Pipeline Artifact
      inputs:
        targetPath: "$(System.DefaultWorkingDirectory)/Resources/Scripts"
        artifactName: ${{ variables.SolutionBaseName }}.Resources.Scripts

    - task: PublishPipelineArtifact@1
      displayName: Publish apim policies
      inputs:
        targetPath: "$(System.DefaultWorkingDirectory)/Resources/ApimPolicy"
        artifactName: ${{ variables.SolutionBaseName }}.Resources.ApimPolicies

- stage: DeployToDevVisits
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to DEV_VISITS
  variables:
  - template: VariableTemplates/DevEnvironmentVariables.yml
  - group: dfc-shared-all
  - group: dfc-app-integrationtests-all
  - group: dfc-shared-dev
  - group: dfc-app-shared-all
  - group: dfc-stax-shared-dev
  - group: dfc-app-shared-dev
  - group: 'KeyVault - dfc-dev-shared-kv'
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ApimPoliciesPath:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ApimPolicies"
      ApimProductId: '$(ApimProductId)'
      ApimLoggerName: '$(ApimLoggerName)'
      APIProductInstanceName: '$(ApimProductInstanceName)'
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      ApimImportScript: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.Scripts/Import-ApimOpenApiDefinitionFromFile.ps1"
      SpecificationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.OpenApiDocs"
      SharedResourceGroup: '$(SharedResourceGroup)'
      ApimServiceName: '$(ApimServiceName)'
      FunctionAppDomain: '$(FunctionAppDomain)'
      FunctionAppName: '$(FunctionAppName)'
      EnvironmentName: DEV_VISITS
      DFCAzureDevOpsProjectGuid: $(DFCAzureDevOpsProjectGuid)
      # The Apis parameter requires a complex object be passed in,  which requires some odd looking yaml.
      # The top level -`s here defines an array of "something"
      # The inner level -'s defines an array of mappings.
      Apis: 
        -
          - name: AddVisit
            azureFunctionName: '${{ variables.WebAppPrefix }}-api-visits-fa'

- stage: DeployToSitVisits
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to SIT_VISITS
  variables:
  - template: VariableTemplates/SitEnvironmentVariables.yml
  - group: dfc-shared-all
  - group: dfc-app-integrationtests-all
  - group: dfc-shared-sit
  - group: dfc-app-shared-all
  - group: dfc-stax-shared-sit
  - group: dfc-app-shared-sit
  - group: 'KeyVault - dfc-sit-shared-kv'
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ApimPoliciesPath:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ApimPolicies"
      ApimProductId: '$(ApimProductId)'
      ApimLoggerName: '$(ApimLoggerName)'
      APIProductInstanceName: '$APIProductInstanceName)'
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      ApimImportScript: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.Scripts/Import-ApimOpenApiDefinitionFromFile.ps1"
      SpecificationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.OpenApiDocs"
      SharedResourceGroup: '$(SharedResourceGroup)'
      ApimServiceName: '$(ApimServiceName)'
      FunctionAppDomain: '$(FunctionAppDomain)'
      FunctionAppName: '$(FunctionAppName)'
      EnvironmentName: SIT_VISITS
      DFCAzureDevOpsProjectGuid: $(DFCAzureDevOpsProjectGuid)
      # The Apis parameter requires a complex object be passed in,  which requires some odd looking yaml.
      # The top level -`s here defines an array of "something"
      # The inner level -'s defines an array of mappings.
      Apis: 
        -
          - name: AddVisit
            azureFunctionName: '${{ variables.WebAppPrefix }}-api-visits-fa'