variables:
- name: FunctionalTestsSqlDatabaseConnStr
  value: 'Server=tcp:$(sharedSqlServerName).database.windows.net,1433;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(FunctionalTestsUser);Password=$(FunctionalTestsUserPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
- name: ReleaseEnvironmentName
  value: DEV
- name: ApimLoggerName
  value: visits-logger
- name: ApimProductId
  value: visits
- name: ApimProductInstanceName
  value: visits
- name: ApiName
  value: visits
- name: ApiVersionNumber
  value: v1
- name: DfcVisitsTestsBuildId
  value: 1
- name: WebAppPrefix
  value: dfc-dev-api
- name: FunctionAppInsightName
  value: $(WebAppPrefix)-visits-ai
- name: FunctionAppName
  value: $(WebAppPrefix)-visits-fa
- name: ResourceGroup
  value: $(WebAppPrefix)-visits-rg
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2